### ISSUE TITLE
Gameplan

### ISSUE THREAD

**Issue by non-binary** [non-binary/http-cache-semantics-old#2]
- [x] Add README, License and create empty Rust project. => #1
- [x] Add function definitions and failing unit tests. => #3
- [ ] Implement functions and their tests one by one. => #4 
- [ ] Test!

https://discourse.entropic.dev/t/looking-for-help-rust-port-of-http-cache-semantics/258
https://github.com/kornelski/http-cache-semantics/blob/master/index.js
https://github.com/kornelski/http-cache-semantics/tree/master/test
https://rust-lang-nursery.github.io/api-guidelines/naming.html

**Comment by zkat** [comment]
This is a good game plan 💃

**Comment by non-binary** [comment]
https://github.com/kornelski/http-cache-semantics uses BDD testing/Mocha but from what I've seen it seems the BDD testing frameworks for Rust are not being maintained anymore and/or require projects to use the `nightly` stream. See https://github.com/reem/stainless and https://github.com/cfrancia/spectral.

@zkat Do you have any recommendations for testing frameworks for Rust? Or shall we use the built in/bog standard unit testing that comes with Rust? https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html

**Comment by zkat** [comment]
No need for a test framework! Rust's built in test mechanism is more than sufficient! And using it just simplifies things a lot.

**Comment by non-binary** [comment]
Sounds good!

**Comment by non-binary** [comment]
#3 is ready to be reviewed. Once reviewed, I'll go ahead and merge then next time I have a change I will start working on implementing the functions and real tests themselves. 💃

**Comment by non-binary** [comment]
@zkat I've been dealing with some health things but I'm going to try to get back on this in the next few days. Thanks for your patience! :)

**Comment by zkat** [comment]
No problem! I hope you feel better soon. 💚
